### ISSUE TITLE
could you please add some explanation on chapter 2?

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/nativescript-angular-guide#1]
``` css
Page {
  background-color: white;
  font-size: 15;
}
```

actually, there is no tag named Page within template of the Component.

 Each Angular2 Component will generate a Page tag outside it's template?
or the whole application just have one Page tag outside the root Component you bootstrap?
